Update limit.py to respond to @bornstei review
limit.py now expects the following format:

- !Limit
  source:   -- telemetry source for the limit. should follow format 'Packet.field_name'
  desc:     -- description of the limit
  units:    -- the units used for possible conversion depending on the units set in the
               telemetry dictionary
  lower:    -- lower limits
    error:  -- trigger error if telemetry value exceeds this lower bound (exclusive)
    warn:   -- trigger warning if telemetry value exceeds this lower bound (exclusive)
  upper:    -- upper limits
    error:  -- trigger error if telemetry value exceeds this upper bound (exclusive)
    warn:   -- trigger warning if telemetry value exceeds this upper bound (exclusive)
  value:    -- enumerated values to trigger error/warning
    error:  -- trigger error if telemetry value == or in list of strings
    warn:   -- trigger warning if telemetry value == or in list of strings

test_limit.py includes updated unit tests

refs #336