Issue #336 - initial limit.yaml reader for limit monitoring
limit.yaml
-----------
Provides examples of the various possible limit formats. The basic schema:

- !Limit
  source:   -- telemetry source for the limit. should follow format 'Packet.field_name'
  desc:     -- description of the limit
  error:    -- either a min/max range or an enum that will cause an error
    min:    -- min range value (exclusive)
    max:    -- max range value (exclusive)
    enum:   -- list of enumeration values that will trigger an error
  warn:     -- same as error, either a min/max range or an enum that will cause an warning
    min:    -- min range value (exclusive)
    max:    -- max range value (exclusive)
    enum:   -- list of enumeration values that will trigger an error

limit.py
--------
Reader for the limit.yaml

test_limit.py
-------------
unit tests for limit.py

config.yaml
-----------
updated with path to limit.yaml