Migrate to bliss.core Python package
It turns out the only sane way [1] to use Python namespace packages
with BLISS is to make the top-level `bliss` module a pure (i.e. empty)
Python namespace package. This requires moving the current modules
under `bliss` to `bliss.core`.  While we're at it, it's probably
better to be more Pythonic and not explicitly import submodules when
`bliss.core` is imported.

The one exception to the above is that importing `bliss.core`,
implicitly imports `bliss.core.cfg`, which in turn creates a singleton
`BlissConfig` object accessible via `bliss.config`.  The rationale for
keeping `bliss.config` is that bootstrapping configuration parameters
and making them easily and uniformly accessible to *all* BLISS modules
and components (e.g. `bliss.core`, `bliss.gui`, etc.) is a fundamental
capability.

That said, this introduces its own oddity:

    import bliss.core

Sets up `bliss.config`.  However, the `bliss` part of `bliss.config`
will not be accessible until `bliss` is explicitly imported.  So,
ultimately, to access `bliss.config`, the following is required:

    import bliss
    import bliss.core

Also, removed:

    1.  bin/bliss_seq_upload.py
    2.  bin/bliss_table_upload.py
    3.  bin/bliss_zlib_upload.py

While refactoring to use `bliss.core`, it became obvious that these
three programs (i.e. the particular mechanics of the uploads) are too
OCO-3 specific.

All unit tests pass.
All command-line programs were successfully tested.

NOTE: Delete your Python pickle (*.pkl) files.  Otherwise, you will
pull out your hair trying to debug mysterious and seemingly
nonsensical errors like the following:

    ImportError: No module named core.cmd

:-/

[1]: @mjjoyce and I tried everything we could think of to avoid going
down this road, but every solution we came up with was brittle in its
own way.